package window;
import route.*;
import function.*;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.net.SocketException;
import java.net.UnknownHostException;
import javax.swing.*;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.MatteBorder;

/**
 *
 * @author cookie
 */
public class InGame extends javax.swing.JFrame {

    /**
     * Creates new form InGame
     */
    public String player1;
    public String player2;
    public String current_player;
    private int p_cur_post, p_next_post, p_rem_post, idx_p_turn = 0, roll_dice = 0;
    private String p_turn = "";
    private BoardMechanic bm = new BoardMechanic();
    private PlayerMechanic[] pm = new PlayerMechanic[2];
    private DatabaseGameConn dbg = new DatabaseGameConn();
    /*    
    private DatabaseConn db = new DatabaseConn();
    */
    private JPanel[] block_map;
    public InGame() {
        initComponents();
        board_div.setBorder(new MatteBorder(0, 0, 0, 4, Color.decode("#99A7FF")));    
        this.block_map = new JPanel[] {this.block_1,this.block_2,this.block_3,this.block_4,this.block_5,this.block_6,this.block_7,this.block_8,this.block_9,this.block_10,this.block_11,this.block_12};
        this.border_turn_p2.setVisible(false);
    }
    public void fetchInfo() {
        System.out.println("--INGAME--");        
        player1_val.setText(this.player1); player2_val.setText(this.player2);
        pm[0] = new PlayerMechanic(); pm[0].setUsername(player1); pm[0].setCurPost(0); pm[0].setColor("#FF9999"); pm[0].border_turn = this.border_turn_p1; pm[0].dice_btn = this.dice_btn;
        pm[1] = new PlayerMechanic(); pm[1].setUsername(player2); pm[1].setCurPost(0); pm[1].setColor("#9996F5"); pm[1].border_turn = this.border_turn_p2; pm[1].dice_btn = this.dice_btn;
        this.p_turn = dbg.getPlayerTurn(player1, player2);
        if (p_turn.equals(pm[0].getUsername())) {idx_p_turn = 0;}
        if (p_turn.equals(pm[1].getUsername())) {idx_p_turn = 1;}             
        if (this.current_player.equals(player1)) {dice_val_lbl.setForeground(Color.decode("#FF9999"));}
        else {dice_val_lbl.setForeground(Color.decode("#9996F5"));}
        
        if (this.current_player.equals(player1)) {
            main_div.setBorder(javax.swing.BorderFactory.createLineBorder(Color.decode("#FF9999"),4));            
            board_div.setBorder(new MatteBorder(0, 0, 0, 4, Color.decode("#FF9999")));                
        } else {
            main_div.setBorder(javax.swing.BorderFactory.createLineBorder(Color.decode("#9996F5"),4));            
            board_div.setBorder(new MatteBorder(0, 0, 0, 4, Color.decode("#9996F5")));                            
        }
        
        dbg.username_p1 = this.player1; dbg.username_p2 = this.player2; dbg.current_player = this.current_player;
        dbg.pm = this.pm;
        dbg.block_map = this.block_map;
        dbg.dice_val_lbl = this.dice_val_lbl;
        dbg.start();
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        main_div = new javax.swing.JPanel();
        board_div = new javax.swing.JPanel();
        block_1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        block_2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        block_3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        block_4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        block_5 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        block_6 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        block_7 = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        block_8 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        block_9 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        block_10 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        block_11 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        block_12 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        dice_div = new javax.swing.JPanel();
        dice_btn = new javax.swing.JButton();
        dice_val_lbl = new javax.swing.JLabel();
        stat_div = new javax.swing.JPanel();
        player1_val = new javax.swing.JLabel();
        player2_val = new javax.swing.JLabel();
        border_turn_p1 = new javax.swing.JPanel();
        border_turn_p2 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        player1_val1 = new javax.swing.JLabel();
        jProgressBar3 = new javax.swing.JProgressBar();
        player1_val2 = new javax.swing.JLabel();
        player1_val3 = new javax.swing.JLabel();
        player1_val4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        main_div.setBackground(new java.awt.Color(255, 255, 255));
        main_div.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 167, 255), 4));

        board_div.setBackground(new java.awt.Color(204, 255, 204));

        block_1.setBackground(new java.awt.Color(255, 255, 255));
        block_1.setBorder(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-finish-flag-64.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);

        javax.swing.GroupLayout block_1Layout = new javax.swing.GroupLayout(block_1);
        block_1.setLayout(block_1Layout);
        block_1Layout.setHorizontalGroup(
            block_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(block_1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        block_1Layout.setVerticalGroup(
            block_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, block_1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        block_2.setBackground(new java.awt.Color(255, 255, 255));
        block_2.setBorder(null);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-fraud-64.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);

        javax.swing.GroupLayout block_2Layout = new javax.swing.GroupLayout(block_2);
        block_2.setLayout(block_2Layout);
        block_2Layout.setHorizontalGroup(
            block_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(block_2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        block_2Layout.setVerticalGroup(
            block_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(block_2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        block_3.setBackground(new java.awt.Color(255, 255, 255));
        block_3.setBorder(null);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-where-to-quest-64.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);

        javax.swing.GroupLayout block_3Layout = new javax.swing.GroupLayout(block_3);
        block_3.setLayout(block_3Layout);
        block_3Layout.setHorizontalGroup(
            block_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(block_3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        block_3Layout.setVerticalGroup(
            block_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(block_3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        block_4.setBackground(new java.awt.Color(255, 255, 255));
        block_4.setBorder(null);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-iceberg-64.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);

        javax.swing.GroupLayout block_4Layout = new javax.swing.GroupLayout(block_4);
        block_4.setLayout(block_4Layout);
        block_4Layout.setHorizontalGroup(
            block_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(block_4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        block_4Layout.setVerticalGroup(
            block_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(block_4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        block_5.setBackground(new java.awt.Color(255, 255, 255));
        block_5.setBorder(null);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-doughnut-64.png"))); // NOI18N
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setFocusPainted(false);

        javax.swing.GroupLayout block_5Layout = new javax.swing.GroupLayout(block_5);
        block_5.setLayout(block_5Layout);
        block_5Layout.setHorizontalGroup(
            block_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(block_5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        block_5Layout.setVerticalGroup(
            block_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(block_5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        block_6.setBackground(new java.awt.Color(255, 255, 255));
        block_6.setBorder(null);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-fraud-64.png"))); // NOI18N
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setFocusPainted(false);

        javax.swing.GroupLayout block_6Layout = new javax.swing.GroupLayout(block_6);
        block_6.setLayout(block_6Layout);
        block_6Layout.setHorizontalGroup(
            block_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(block_6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 68, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        block_6Layout.setVerticalGroup(
            block_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(block_6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        block_7.setBackground(new java.awt.Color(255, 255, 255));
        block_7.setBorder(null);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-muscle-flexing-64.png"))); // NOI18N
        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        jButton15.setFocusPainted(false);

        javax.swing.GroupLayout block_7Layout = new javax.swing.GroupLayout(block_7);
        block_7.setLayout(block_7Layout);
        block_7Layout.setHorizontalGroup(
            block_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(block_7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 68, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        block_7Layout.setVerticalGroup(
            block_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(block_7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        block_8.setBackground(new java.awt.Color(255, 255, 255));
        block_8.setBorder(null);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-blow-64.png"))); // NOI18N
        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jButton13.setFocusPainted(false);

        javax.swing.GroupLayout block_8Layout = new javax.swing.GroupLayout(block_8);
        block_8.setLayout(block_8Layout);
        block_8Layout.setHorizontalGroup(
            block_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(block_8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 68, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        block_8Layout.setVerticalGroup(
            block_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(block_8Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        block_9.setBackground(new java.awt.Color(255, 255, 255));
        block_9.setBorder(null);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-where-to-quest-64.png"))); // NOI18N
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setFocusPainted(false);

        javax.swing.GroupLayout block_9Layout = new javax.swing.GroupLayout(block_9);
        block_9.setLayout(block_9Layout);
        block_9Layout.setHorizontalGroup(
            block_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(block_9Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        block_9Layout.setVerticalGroup(
            block_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(block_9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        block_10.setBackground(new java.awt.Color(255, 255, 255));
        block_10.setBorder(null);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-iceberg-64.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusPainted(false);

        javax.swing.GroupLayout block_10Layout = new javax.swing.GroupLayout(block_10);
        block_10.setLayout(block_10Layout);
        block_10Layout.setHorizontalGroup(
            block_10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(block_10Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        block_10Layout.setVerticalGroup(
            block_10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(block_10Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        block_11.setBackground(new java.awt.Color(255, 255, 255));
        block_11.setBorder(null);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-time-machine-64.png"))); // NOI18N
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setFocusPainted(false);

        javax.swing.GroupLayout block_11Layout = new javax.swing.GroupLayout(block_11);
        block_11.setLayout(block_11Layout);
        block_11Layout.setHorizontalGroup(
            block_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(block_11Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 68, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        block_11Layout.setVerticalGroup(
            block_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(block_11Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        block_12.setBackground(new java.awt.Color(255, 255, 255));
        block_12.setBorder(null);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-bribery-64.png"))); // NOI18N
        jButton14.setBorderPainted(false);
        jButton14.setContentAreaFilled(false);
        jButton14.setFocusPainted(false);

        javax.swing.GroupLayout block_12Layout = new javax.swing.GroupLayout(block_12);
        block_12.setLayout(block_12Layout);
        block_12Layout.setHorizontalGroup(
            block_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(block_12Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 68, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        block_12Layout.setVerticalGroup(
            block_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(block_12Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        dice_div.setBackground(new java.awt.Color(255, 255, 204));

        dice_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-dice-96.png"))); // NOI18N
        dice_btn.setBorderPainted(false);
        dice_btn.setContentAreaFilled(false);
        dice_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dice_btn.setFocusPainted(false);
        dice_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dice_btnActionPerformed(evt);
            }
        });

        dice_val_lbl.setFont(new java.awt.Font("JetBrains Mono", 1, 36)); // NOI18N
        dice_val_lbl.setForeground(new java.awt.Color(153, 150, 245));
        dice_val_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dice_val_lbl.setText("--");

        javax.swing.GroupLayout dice_divLayout = new javax.swing.GroupLayout(dice_div);
        dice_div.setLayout(dice_divLayout);
        dice_divLayout.setHorizontalGroup(
            dice_divLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dice_divLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dice_btn)
                .addGap(40, 40, 40))
            .addGroup(dice_divLayout.createSequentialGroup()
                .addComponent(dice_val_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dice_divLayout.setVerticalGroup(
            dice_divLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dice_divLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(dice_btn)
                .addGap(18, 18, 18)
                .addComponent(dice_val_lbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout board_divLayout = new javax.swing.GroupLayout(board_div);
        board_div.setLayout(board_divLayout);
        board_divLayout.setHorizontalGroup(
            board_divLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(board_divLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(board_divLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(board_divLayout.createSequentialGroup()
                        .addComponent(block_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(block_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(block_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(board_divLayout.createSequentialGroup()
                        .addComponent(block_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(block_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(block_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(board_divLayout.createSequentialGroup()
                        .addGroup(board_divLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(block_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(block_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dice_div, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(board_divLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(block_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(block_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(block_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(block_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        board_divLayout.setVerticalGroup(
            board_divLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(board_divLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(board_divLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(block_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(block_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(block_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(block_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(board_divLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(board_divLayout.createSequentialGroup()
                        .addComponent(block_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(block_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(block_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(board_divLayout.createSequentialGroup()
                        .addComponent(block_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(block_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(block_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(board_divLayout.createSequentialGroup()
                        .addComponent(dice_div, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(board_divLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(block_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(block_3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        stat_div.setBackground(new java.awt.Color(255, 255, 255));

        player1_val.setFont(new java.awt.Font("JetBrains Mono", 3, 15)); // NOI18N
        player1_val.setForeground(new java.awt.Color(255, 153, 153));
        player1_val.setText("SUPERCOOKIE");

        player2_val.setFont(new java.awt.Font("JetBrains Mono", 3, 15)); // NOI18N
        player2_val.setForeground(new java.awt.Color(153, 150, 245));
        player2_val.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        player2_val.setText("NAZARETH666");

        border_turn_p1.setBackground(new java.awt.Color(255, 153, 153));
        border_turn_p1.setPreferredSize(new java.awt.Dimension(0, 5));

        javax.swing.GroupLayout border_turn_p1Layout = new javax.swing.GroupLayout(border_turn_p1);
        border_turn_p1.setLayout(border_turn_p1Layout);
        border_turn_p1Layout.setHorizontalGroup(
            border_turn_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        border_turn_p1Layout.setVerticalGroup(
            border_turn_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        border_turn_p2.setBackground(new java.awt.Color(153, 150, 245));
        border_turn_p2.setPreferredSize(new java.awt.Dimension(0, 5));

        javax.swing.GroupLayout border_turn_p2Layout = new javax.swing.GroupLayout(border_turn_p2);
        border_turn_p2.setLayout(border_turn_p2Layout);
        border_turn_p2Layout.setHorizontalGroup(
            border_turn_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        border_turn_p2Layout.setVerticalGroup(
            border_turn_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jProgressBar1.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBar1.setForeground(new java.awt.Color(255, 153, 153));
        jProgressBar1.setMaximum(1000);
        jProgressBar1.setValue(1000);
        jProgressBar1.setBorder(null);
        jProgressBar1.setBorderPainted(false);

        player1_val1.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        player1_val1.setForeground(new java.awt.Color(255, 153, 153));
        player1_val1.setText("HP");

        jProgressBar3.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBar3.setForeground(new java.awt.Color(153, 150, 245));
        jProgressBar3.setMaximum(1000);
        jProgressBar3.setValue(1000);
        jProgressBar3.setBorder(null);
        jProgressBar3.setBorderPainted(false);

        player1_val2.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        player1_val2.setForeground(new java.awt.Color(153, 150, 245));
        player1_val2.setText("HP");

        player1_val3.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        player1_val3.setForeground(new java.awt.Color(255, 153, 153));
        player1_val3.setText("BLOCK-SKILL: ");

        player1_val4.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        player1_val4.setForeground(new java.awt.Color(102, 102, 102));
        player1_val4.setText("CANNON-O-BOOM");

        jScrollPane2.setBorder(null);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(102, 102, 102));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Cannon-o-Boom merupakan senjata andalan seluruh player. Damage nya yang besar menjanjikan kemenangan yang hakiki\n--\nDamage : 150");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jScrollPane2.setViewportView(jTextArea1);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-book-64.png"))); // NOI18N
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setFocusPainted(false);

        javax.swing.GroupLayout stat_divLayout = new javax.swing.GroupLayout(stat_div);
        stat_div.setLayout(stat_divLayout);
        stat_divLayout.setHorizontalGroup(
            stat_divLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stat_divLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stat_divLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, stat_divLayout.createSequentialGroup()
                        .addGroup(stat_divLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(border_turn_p1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(player1_val, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(stat_divLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(player2_val, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(border_turn_p2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, stat_divLayout.createSequentialGroup()
                        .addComponent(player1_val1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, stat_divLayout.createSequentialGroup()
                        .addComponent(player1_val2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, stat_divLayout.createSequentialGroup()
                        .addComponent(player1_val3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player1_val4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(stat_divLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        stat_divLayout.setVerticalGroup(
            stat_divLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stat_divLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stat_divLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player1_val)
                    .addComponent(player2_val))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(stat_divLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(border_turn_p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(border_turn_p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(stat_divLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(player1_val1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(stat_divLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(player1_val2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(stat_divLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player1_val3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(player1_val4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addContainerGap())
        );

        javax.swing.GroupLayout main_divLayout = new javax.swing.GroupLayout(main_div);
        main_div.setLayout(main_divLayout);
        main_divLayout.setHorizontalGroup(
            main_divLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_divLayout.createSequentialGroup()
                .addComponent(board_div, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stat_div, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        main_divLayout.setVerticalGroup(
            main_divLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(board_div, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(stat_div, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_div, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_div, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dice_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dice_btnActionPerformed
        // TODO add your handling code here:
        this.p_turn = dbg.getPlayerTurn(player1, player2);
        if (this.p_turn.equals(this.current_player)) {            
            bm = new BoardMechanic();
            bm.setObjPlayer(pm);        
            bm.setBlockMap(this.block_map); 
            bm.setDiceVal(dice_val_lbl);
            bm.setPlayerTurn(p_turn);
            this.p_cur_post = dbg.getPlayerCurPost(player1, player2, p_turn);
            this.roll_dice = bm.rollDice();
            this.p_next_post = this.p_cur_post + this.roll_dice;
            if (this.p_next_post > 11) {
                this.p_rem_post = this.p_next_post - 12;
                this.p_next_post = 11;
            } else {this.p_rem_post = -1;}
            bm.setPlayerPost(this.p_cur_post,this.p_next_post,this.p_rem_post,this.roll_dice);
            bm.start();
        }
    }//GEN-LAST:event_dice_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel block_1;
    private javax.swing.JPanel block_10;
    private javax.swing.JPanel block_11;
    private javax.swing.JPanel block_12;
    private javax.swing.JPanel block_2;
    private javax.swing.JPanel block_3;
    private javax.swing.JPanel block_4;
    private javax.swing.JPanel block_5;
    private javax.swing.JPanel block_6;
    private javax.swing.JPanel block_7;
    private javax.swing.JPanel block_8;
    private javax.swing.JPanel block_9;
    private javax.swing.JPanel board_div;
    private javax.swing.JPanel border_turn_p1;
    private javax.swing.JPanel border_turn_p2;
    private javax.swing.JButton dice_btn;
    private javax.swing.JPanel dice_div;
    private javax.swing.JLabel dice_val_lbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel main_div;
    private javax.swing.JLabel player1_val;
    private javax.swing.JLabel player1_val1;
    private javax.swing.JLabel player1_val2;
    private javax.swing.JLabel player1_val3;
    private javax.swing.JLabel player1_val4;
    private javax.swing.JLabel player2_val;
    private javax.swing.JPanel stat_div;
    // End of variables declaration//GEN-END:variables
}
